BookStore/Models/Orders/IOrderRepository.cs
using BookStore.Models.OrderItems;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Orders
{
    public interface IOrderRepository
    {
        Task<IEnumerable<Order>> GetAllAsync();
        Task<IEnumerable<Order>> GetAllSortedByOrderPlacedDescAsync();
        Task<IEnumerable<Order>> GetAllByCustomerIdAsync(int customerId);
        Task<Order> GetByIdAsync(int orderId);
        Task<Order> AddAsync(Order order);
        Task<Order> UpdateAsync(Order orderChanges);
        Task<Order> DeleteAsync(int orderId);

        //void AddOrderItemToOrder(OrderItem orderItem);
        bool RemoveOrderItemFromOrder(OrderItem orderItem);
    }
}

BookStore/Models/Orders/MockOrderRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Extensions;
using BookStore.Models.Books;
using BookStore.Models.Carts;
using BookStore.Models.OrderItems;
using BookStore.Utilities;
using Microsoft.AspNetCore.Http;

namespace BookStore.Models.Orders
{
    public class MockOrderRepository : IOrderRepository
    {
        IList<Order> _ordersList;

        public MockOrderRepository()
        {
            this._ordersList = new List<Order>();
        }

        public async Task<Order> AddAsync(Order order)
        {
            order.Id = (_ordersList.Count > 0) ? _ordersList.Max(o => o.Id) + 1 : 1;
            _ordersList.Add(order);
            return order;
        }

        public async Task<Order> DeleteAsync(int orderId)
        {
            Order order = _ordersList.FirstOrDefault(o => o.Id == orderId);

            if (order != null)
            {
                _ordersList.Remove(order);
            }

            return order;
        }

        public async Task<IEnumerable<Order>> GetAllAsync() 
            => _ordersList;

        public async Task<IEnumerable<Order>> GetAllByCustomerIdAsync(int customerId)
        {
            //_ordersList.Where(o => o.CustomerId == customerId)
            throw new NotImplementedException();
        }

        public async Task<IEnumerable<Order>> GetAllSortedByOrderPlacedDescAsync()
            => _ordersList.OrderByDescending(o => o.OrderPlaced);

        public async Task<Order> GetByIdAsync(int orderId) 
            => _ordersList.FirstOrDefault(o => o.Id == orderId);

        public bool RemoveOrderItemFromOrder(OrderItem orderItem)
        {
            throw new NotImplementedException();
        }

        public async Task<Order> UpdateAsync(Order orderChanges)
        {
            throw new NotImplementedException();
        }
    }
}

BookStore/Models/Orders/Order.cs
using BookStore.Models.OrderItems;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Orders
{
    public class Order
    {
        public int Id { get; set; }

        [Display(Name = "Order placed")]
        public DateTime OrderPlaced { get; set; }

        public DateTime? OrderFulfilled { get; set; }

        public ICollection<OrderItem> OrderItems { get; set; }
    }
}

BookStore/Models/Orders/SqlOrderRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models.OrderItems;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Models.Orders
{
    public class SqlOrderRepository : IOrderRepository
    {
        private readonly AppDbContext _context;

        public SqlOrderRepository(AppDbContext context)
        {
            this._context = context;
        }

        public async Task<Order> AddAsync(Order order)
        {
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();

            return order;
        }

        public async Task<Order> DeleteAsync(int orderId)
        {
            Order order = await _context.Orders.Include(o => o.OrderItems).FirstOrDefaultAsync(o => o.Id == orderId);

            if (order != null)
            {
                // Delete all items belonging to the order before deleting it
                // TODO: move removing OrderItems to SqlOrderItemRepository
                _context.OrderItems.RemoveRange(order.OrderItems);

                _context.Orders.Remove(order);
                await _context.SaveChangesAsync();
            }

            return order;
        }

        public async Task<IEnumerable<Order>> GetAllAsync()
            => await _context.Orders
                .Include(o => o.OrderItems)
                    .ThenInclude(oi => oi.Book)
                .ToListAsync();

        public async Task<IEnumerable<Order>> GetAllSortedByOrderPlacedDescAsync()
            => await _context.Orders
                .Include(o => o.OrderItems)
                    .ThenInclude(oi => oi.Book)
                .OrderByDescending(o => o.OrderPlaced)
                .ToListAsync();

        public async Task<IEnumerable<Order>> GetAllByCustomerIdAsync(int customerId)
        {
            throw new NotImplementedException();
        }

        public async Task<Order> GetByIdAsync(int orderId)
            => await _context.Orders
                .Include(o => o.OrderItems)
                    .ThenInclude(oi => oi.Book)
                .FirstOrDefaultAsync(o => o.Id == orderId);

        public bool RemoveOrderItemFromOrder(OrderItem orderItem)
        {
            throw new NotImplementedException();
        }

        public async Task<Order> UpdateAsync(Order orderChanges)
        {
            throw new NotImplementedException();
        }
    }
}

BookStore/Controllers/BookController.cs
using BookStore.ModelBinders;
using BookStore.Models;
using BookStore.Models.Books;
using BookStore.Models.Carts;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ICartRepository _cartRepository;

        public BookController(IBookRepository bookRepository, IWebHostEnvironment webHostEnvironment, ICartRepository cartRepository)
        {
            this._bookRepository = bookRepository;
            this._webHostEnvironment = webHostEnvironment;
            this._cartRepository = cartRepository;
        }

        //--------------------------------------------------------------
        public IActionResult Index() => View(_bookRepository.GetAll());

        //--------------------------------------------------------------
        public IActionResult Details(int id) => View(_bookRepository.GetById(id));

        //--------------------------------------------------------------
        [HttpGet]
        public IActionResult Create() => View();

        //--------------------------------------------------------------
        [HttpPost]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>")]
        public IActionResult Create(
            [Bind("Title,Author,Description,Price,Photo")]
            BookCreateViewModel bookCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookCreateViewModel);
            }

            string photoUniqueName = null;

            if (bookCreateViewModel.Photo != null)
            {
                string serverImagesFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                photoUniqueName = Guid.NewGuid() + "_" + bookCreateViewModel.Photo.FileName;
                string serverImageLocation = Path.Combine(serverImagesFolder, photoUniqueName);

                using (FileStream fileStream = new FileStream(serverImageLocation, FileMode.Create))
                {
                    bookCreateViewModel.Photo.CopyTo(fileStream);
                }
            }

            Book book = new Book
            {
                Title = bookCreateViewModel.Title,
                Author = bookCreateViewModel.Author,
                Price = bookCreateViewModel.Price,
                Description = bookCreateViewModel.Description,
                PhotoUniqueName = photoUniqueName
            };

            _bookRepository.Add(book);

            return RedirectToAction(nameof(Details), new { id = book.Id });
        }

        //--------------------------------------------------------------
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Book book = _bookRepository.GetById(id);

            if (book != null)
            {
                BookEditViewModel bookEditViewModel = new BookEditViewModel
                {
                    Id = book.Id,
                    Title = book.Title,
                    Author = book.Author,
                    Price = book.Price,
                    Description = book.Description,
                    ExistingPhotoUniqueName = book.PhotoUniqueName
                };

                return View(bookEditViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        //--------------------------------------------------------------
        [HttpPost]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>")]
        public IActionResult Edit(
            [Bind("Id,Title,Author,Description,Price,Photo,ExistingPhotoUniqueName")]
            BookEditViewModel bookEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookEditViewModel);
            }

            string photoUniqueName;

            if (bookEditViewModel.Photo != null)
            {
                string serverImagesFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                photoUniqueName = Guid.NewGuid() + "_" + bookEditViewModel.Photo.FileName;
                string serverImageLocation = Path.Combine(serverImagesFolder, photoUniqueName);

                using (FileStream fileStream = new FileStream(serverImageLocation, FileMode.Create))
                {
                    bookEditViewModel.Photo.CopyTo(fileStream);
                }
            }
            else
            {
                photoUniqueName = bookEditViewModel.ExistingPhotoUniqueName;
            }

            Book book = new Book
            {
                Id = bookEditViewModel.Id,
                Title = bookEditViewModel.Title,
                Author = bookEditViewModel.Author,
                Price = bookEditViewModel.Price,
                Description = bookEditViewModel.Description,
                PhotoUniqueName = photoUniqueName
            };

            _bookRepository.Update(book);

            return RedirectToAction("Details", new { id = book.Id });
        }

        //--------------------------------------------------------------
        public IActionResult Delete(int id)
        {
            // If book to delete is in the shopping cart display error
            if (_cartRepository.GetCartItemById(id) != null)
            {
                // http response code 409 is for conflict that prevents the action from being performed
                Response.StatusCode = 409; 
                ViewData["whyBookIsNonRemovable"] = "in-cart";
                return View("NonRemovableBook", id);
            }

            Book deletedBoook = _bookRepository.Delete(id);

            if (deletedBoook == null)
            {
                // http response code 409 is for conflict that prevents the action from being performed
                Response.StatusCode = 409;
                return View("NonRemovableBook", id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Models;
using BookStore.Models.Orders;
using BookStore.Models.Carts;
using BookStore.Models.OrderItems;
using BookStore.Models.Books;

namespace BookStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ICartRepository _cartRepository;
        private readonly IBookRepository _bookRepository;
        private readonly IOrderItemRepository _orderItemRepository;

        public OrderController(
            IOrderRepository orderRepository,
            ICartRepository cartRepository,
            IBookRepository bookRepository,
            IOrderItemRepository orderItemRepository)
        {
            this._orderRepository = orderRepository;
            this._cartRepository = cartRepository;
            this._bookRepository = bookRepository;
            this._orderItemRepository = orderItemRepository;
        }

        public async Task<IActionResult> Index()
            => View(await _orderRepository.GetAllSortedByOrderPlacedDescAsync());

        public async Task<IActionResult> Details(int id)
        {
            Order order = await _orderRepository.GetByIdAsync(id);

            if (order == null) return RedirectToAction(nameof(Index));

            IEnumerable<OrderItem> orderItems = order.OrderItems;

            return View(orderItems);
        }

        public async Task<IActionResult> Create()
        {
            Order order = new Order
            {
                OrderPlaced = DateTime.UtcNow,
                OrderItems = await this.GetOrderItemsWithAssignedIdAsyc()
            };

            await _orderRepository.AddAsync(order);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _orderRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // Private utility methods --------------------------------------------

        private async Task<IEnumerable<OrderItem>> GetAllOrderItemsFromCartContentAsync()
        {
            // TODO: make GetById asynchronous and add await here
            // CartItem inherits from the OrderItem
            IEnumerable<OrderItem> orderItems = _cartRepository.GetAllCartItems();

            // TODO: Try to find a better place to clear the shopping cart
            _cartRepository.ClearCart();

            return orderItems;
        }

        private async Task<IList<OrderItem>> GetOrderItemsWithAssignedIdAsyc()
        {
            IList<OrderItem> orderItemsWithId = new List<OrderItem>();

            foreach (OrderItem orderItem in await this.GetAllOrderItemsFromCartContentAsync())
            {
                orderItemsWithId.Add(await _orderItemRepository.AddAsync(orderItem));
            }

            return orderItemsWithId;
        }
    }
}

BookStore/Views/Order/Details.cshtml
@model IEnumerable<OrderItem>

@{
    ViewData["Title"] = "Order details";
}

@if (Model.Count() == 0)
{
    <h3 class="font-weight-normal mb-3 pt-2">Order is empty</h3>
}
else
{
    <h3 class="font-weight-normal mb-3 pt-2">Order details</h3>

    //TODO: Check responsiveness of the table
    <table class="table border-bottom w-auto">
        <thead>
            <tr class="bg-light">
                <th class="border-bottom-0"></th>
                <th class="border-bottom-0">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Book.Title)
                </th>
                <th class="border-bottom-0">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Quantity)
                </th>
                @*<th class="border-bottom-0"></th>*@
                <th class="border-bottom-0">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Book.Price)
                </th>
            </tr>
        </thead>

        <tbody>
            @{decimal totalPrice = 0; }

            @foreach (var orderItem in Model)
            {
                decimal orderItemPrice = orderItem.Book.Price * orderItem.Quantity;
                totalPrice += orderItemPrice;
                var photoPath = "~/images/" + (orderItem.Book.PhotoUniqueName ?? SD.NoImage);

                <tr>
                    <td class="align-middle text-right">
                        <img src=@photoPath style="height:100px" asp-append-version="true" alt="Book cover" />
                    </td>
                    <td class="align-middle"> @orderItem.Book.Title </td>
                    <td class="align-middle text-center"> @orderItem.Quantity </td>
                    @*<td class="align-middle">
                        <div class="d-flex">
                            <a asp-action="AddOrderItemToOrder" asp-route-id="@orderItem.Book.Id" class="btn btn-outline-secondary mr-1" style="width:2.5em">+</a>
                            <a asp-action="RemoveOrderItemFromOrder" asp-route-id="@orderItem.Book.Id" class="btn btn-outline-secondary" style="width:2.5em">–</a>
                        </div>
                    </td>*@
                    <td class="align-middle text-center"> @($"{orderItemPrice:C2}")</td>
                </tr>
            }
            <tr class="bg-light">
                <td></td>
                <td></td>
                @*<td></td>*@
                <td><strong>Total price:</strong></td>
                <td><strong>@($"{totalPrice:C2}")</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="d-flex">
        <a asp-controller="Order" asp-action="Index" class="btn btn-secondary mr-2">Back to order list</a>
    </div>
}

BookStore/Views/Order/Index.cshtml
@model IEnumerable<Order>

@{
    ViewData["Title"] = "Order index";
}

@if (Model.Count() == 0)
{
    <h3 class="font-weight-normal mb-3 pt-2">No orders</h3>
}
else
{
    <h3 class="font-weight-normal mb-3 pt-2">Order index</h3>

    <table class="table border-bottom w-auto">
        <thead>
            <tr class="bg-light">
                <th class="border-bottom-0">
                    #
                </th>
                <th class="border-bottom-0">
                    @Html.DisplayNameFor(model => model.OrderPlaced)
                </th>
                <th class="border-bottom-0">
                    Order price
                </th>
                <th class="border-bottom-0"></th>
            </tr>
        </thead>
        <tbody>
            @{int pos = 1; }
            @foreach (var order in Model)
            {
                <tr>
                    <td class="align-middle">@pos</td>
                    @{pos++;}

                    <td class="align-middle">
                        @order.OrderPlaced.ToLocalTime()
                    </td>

                    @{ decimal orderPrice = 0;}
                    @foreach (var orderItem in order.OrderItems)
                    {
                        orderPrice += orderItem.Quantity * orderItem.Book.Price;
                    }
                    <td class="align-middle">
                        @($"{orderPrice:C2}")
                    </td>

                    <td class="align-middle">
                        <div class="d-flex">
                            <a asp-action="Details" asp-route-id="@order.Id" class="btn btn-primary mr-2">Details</a>
                            <a asp-action="Delete" asp-route-id="@order.Id" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-controller="Book" asp-action="Index" class="btn btn-secondary">Back to shopping</a> 
}