BookStore/Models/Book/Book.cs
using BookStore.ModelBinders;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
  public class Book
  {
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Author { get; set; }

    public string Description { get; set; }

    [Range(0.01, 100000)]
    [Required]
    public decimal Price { get; set; }

    public string PhotoUniqueName { get; set; }
  }
}

BookStore/Models/Book/IBookRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
  public interface IBookRepository
  {
    Book GetById(int id);
    IEnumerable<Book> GetAll();
    Book Add(Book book);
    Book Update(Book book);
    Book Delete(int id);
  }
}

BookStore/Models/Book/MockBookRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
  public class MockBookRepository : IBookRepository
  {
    private readonly IList<Book> _bookList;

    public MockBookRepository()
    {
      _bookList = new List<Book>
      {
        new Book{Id=1, Author="Author1", Title="Title1", Price=10.515m},
        new Book{Id=2, Author="Author2", Title="Title2", Price=5.5m},
        new Book{Id=3, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=4, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=5, Author="Author3", Title="Title3", Price=5.1551m},
        new Book{Id=6, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=7, Author="Author3", Title="Title3", Price=5.1111m}
      };
    }

    //--------------------------------------------------------------
    public Book Add(Book book)
    {
      book.Id = _bookList.Max(b => b.Id) + 1;
      _bookList.Add(book);

      return book;
    }

    //--------------------------------------------------------------
    public Book Delete(int id)
    {
      Book book = _bookList.FirstOrDefault(b => b.Id == id);

      if (book != null)
      {
        _bookList.Remove(book);
      }

      return book;
    }

    //--------------------------------------------------------------
    public IEnumerable<Book> GetAll() => _bookList;

    //--------------------------------------------------------------
    public Book GetById(int id) => _bookList.FirstOrDefault(b => b.Id == id);

    //--------------------------------------------------------------
    public Book Update(Book bookChanges)
    {
      Book book = _bookList.FirstOrDefault(b => b.Id == bookChanges.Id);

      if (book != null) {
        book.Title = bookChanges.Title;
        book.Author = bookChanges.Author;
        book.Description = bookChanges.Description;
        book.Price = bookChanges.Price;
        book.PhotoUniqueName = bookChanges.PhotoUniqueName;
      }

      return book;
    }
  }
}

BookStore/Models/Book/SqlBookRepository.cs
using BookStore.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Models
{
  public class SqlBookRepository : IBookRepository
  {
    private readonly AppDbContext _dbContext;

    public SqlBookRepository(AppDbContext context)
    {
      this._dbContext = context;
    }

    public Book Add(Book book)
    {
      _dbContext.Books.Add(book);
      _dbContext.SaveChanges();

      return book;
    }

    public Book Delete(int id)
    {
      Book book = _dbContext.Books.Find(id);

      if (book != null)
      {
        _dbContext.Books.Remove(book);
        _dbContext.SaveChanges();
      }

      return book;
    }

    public IEnumerable<Book> GetAll() => _dbContext.Books;

    public Book GetById(int id) => _dbContext.Books.Find(id);

    public Book Update(Book bookChanges)
    {
      EntityEntry book = _dbContext.Books.Attach(bookChanges);
      book.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
      _dbContext.SaveChanges();

      return bookChanges;
    }
  }
}

BookStore/Models/Books/Book.cs
using BookStore.ModelBinders;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Books
{
  public class Book
  {
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Author { get; set; }

    public string Description { get; set; }

    [Range(0.01, 100000)]
    [Required]
    public decimal Price { get; set; }

    public string PhotoUniqueName { get; set; }
  }
}

BookStore/Models/Books/IBookRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Books
{
  public interface IBookRepository
  {
    Book GetById(int id);
    IEnumerable<Book> GetAll();
    Book Add(Book book);
    Book Update(Book book);
    Book Delete(int id);
  }
}

BookStore/Models/Books/MockBookRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Books
{
  public class MockBookRepository : IBookRepository
  {
    private readonly IList<Book> _bookList;

    public MockBookRepository()
    {
      _bookList = new List<Book>
      {
        new Book{Id=1, Author="Author1", Title="Title1", Price=10.515m},
        new Book{Id=2, Author="Author2", Title="Title2", Price=5.5m},
        new Book{Id=3, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=4, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=5, Author="Author3", Title="Title3", Price=5.1551m},
        new Book{Id=6, Author="Author3", Title="Title3", Price=5.1111m},
        new Book{Id=7, Author="Author3", Title="Title3", Price=5.1111m}
      };
    }

    //--------------------------------------------------------------
    public Book Add(Book book)
    {
      book.Id = _bookList.Max(b => b.Id) + 1;
      _bookList.Add(book);

      return book;
    }

    //--------------------------------------------------------------
    public Book Delete(int id)
    {
      Book book = _bookList.FirstOrDefault(b => b.Id == id);

      if (book != null)
      {
        _bookList.Remove(book);
      }

      return book;
    }

    //--------------------------------------------------------------
    public IEnumerable<Book> GetAll() => _bookList;

    //--------------------------------------------------------------
    public Book GetById(int id) => _bookList.FirstOrDefault(b => b.Id == id);

    //--------------------------------------------------------------
    public Book Update(Book bookChanges)
    {
      Book book = _bookList.FirstOrDefault(b => b.Id == bookChanges.Id);

      if (book != null) {
        book.Title = bookChanges.Title;
        book.Author = bookChanges.Author;
        book.Description = bookChanges.Description;
        book.Price = bookChanges.Price;
        book.PhotoUniqueName = bookChanges.PhotoUniqueName;
      }

      return book;
    }
  }
}

BookStore/Models/Books/SqlBookRepository.cs
using BookStore.Models;
using BookStore.Models.Carts;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.Books
{
    public class SqlBookRepository : IBookRepository
    {
        private readonly AppDbContext _dbContext;

        public SqlBookRepository(AppDbContext context)
        {
            this._dbContext = context;
        }

        public Book Add(Book book)
        {
            _dbContext.Books.Add(book);
            _dbContext.SaveChanges();

            return book;
        }

        // TODO: Implement the same for MockBookRepository?
        public Book Delete(int id)
        {
            Book book = _dbContext.Books.Find(id);

            try
            {
                if (book != null)
                {
                    // TODO: add checking if the book to delete is a part of an existing order
                    _dbContext.Books.Remove(book);
                    _dbContext.SaveChanges();
                }
            }
            catch (Exception e) // Because book is a part of existing order
            {
                return null;
            }

            return book;
        }

        public IEnumerable<Book> GetAll() => _dbContext.Books;

        public Book GetById(int id) => _dbContext.Books.Find(id);

        public Book Update(Book bookChanges)
        {
            EntityEntry book = _dbContext.Books.Attach(bookChanges);
            book.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _dbContext.SaveChanges();

            return bookChanges;
        }
    }
}

BookStore/Controllers/BookController.cs
using BookStore.ModelBinders;
using BookStore.Models;
using BookStore.Models.Books;
using BookStore.Models.Carts;
using BookStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ICartRepository _cartRepository;

        public BookController(IBookRepository bookRepository, IWebHostEnvironment webHostEnvironment, ICartRepository cartRepository)
        {
            this._bookRepository = bookRepository;
            this._webHostEnvironment = webHostEnvironment;
            this._cartRepository = cartRepository;
        }

        //--------------------------------------------------------------
        public IActionResult Index() => View(_bookRepository.GetAll());

        //--------------------------------------------------------------
        public IActionResult Details(int id) => View(_bookRepository.GetById(id));

        //--------------------------------------------------------------
        [HttpGet]
        public IActionResult Create() => View();

        //--------------------------------------------------------------
        [HttpPost]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>")]
        public IActionResult Create(
            [Bind("Title,Author,Description,Price,Photo")]
            BookCreateViewModel bookCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookCreateViewModel);
            }

            string photoUniqueName = null;

            if (bookCreateViewModel.Photo != null)
            {
                string serverImagesFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                photoUniqueName = Guid.NewGuid() + "_" + bookCreateViewModel.Photo.FileName;
                string serverImageLocation = Path.Combine(serverImagesFolder, photoUniqueName);

                using (FileStream fileStream = new FileStream(serverImageLocation, FileMode.Create))
                {
                    bookCreateViewModel.Photo.CopyTo(fileStream);
                }
            }

            Book book = new Book
            {
                Title = bookCreateViewModel.Title,
                Author = bookCreateViewModel.Author,
                Price = bookCreateViewModel.Price,
                Description = bookCreateViewModel.Description,
                PhotoUniqueName = photoUniqueName
            };

            _bookRepository.Add(book);

            return RedirectToAction(nameof(Details), new { id = book.Id });
        }

        //--------------------------------------------------------------
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Book book = _bookRepository.GetById(id);

            if (book != null)
            {
                BookEditViewModel bookEditViewModel = new BookEditViewModel
                {
                    Id = book.Id,
                    Title = book.Title,
                    Author = book.Author,
                    Price = book.Price,
                    Description = book.Description,
                    ExistingPhotoUniqueName = book.PhotoUniqueName
                };

                return View(bookEditViewModel);
            }

            return RedirectToAction(nameof(Index));
        }

        //--------------------------------------------------------------
        [HttpPost]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>")]
        public IActionResult Edit(
            [Bind("Id,Title,Author,Description,Price,Photo,ExistingPhotoUniqueName")]
            BookEditViewModel bookEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(bookEditViewModel);
            }

            string photoUniqueName;

            if (bookEditViewModel.Photo != null)
            {
                string serverImagesFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                photoUniqueName = Guid.NewGuid() + "_" + bookEditViewModel.Photo.FileName;
                string serverImageLocation = Path.Combine(serverImagesFolder, photoUniqueName);

                using (FileStream fileStream = new FileStream(serverImageLocation, FileMode.Create))
                {
                    bookEditViewModel.Photo.CopyTo(fileStream);
                }
            }
            else
            {
                photoUniqueName = bookEditViewModel.ExistingPhotoUniqueName;
            }

            Book book = new Book
            {
                Id = bookEditViewModel.Id,
                Title = bookEditViewModel.Title,
                Author = bookEditViewModel.Author,
                Price = bookEditViewModel.Price,
                Description = bookEditViewModel.Description,
                PhotoUniqueName = photoUniqueName
            };

            _bookRepository.Update(book);

            return RedirectToAction("Details", new { id = book.Id });
        }

        //--------------------------------------------------------------
        public IActionResult Delete(int id)
        {
            // If book to delete is in the shopping cart display error
            if (_cartRepository.GetCartItemById(id) != null)
            {
                // http response code 409 is for conflict that prevents the action from being performed
                Response.StatusCode = 409; 
                ViewData["whyBookIsNonRemovable"] = "in-cart";
                return View("NonRemovableBook", id);
            }

            Book deletedBoook = _bookRepository.Delete(id);

            if (deletedBoook == null)
            {
                // http response code 409 is for conflict that prevents the action from being performed
                Response.StatusCode = 409;
                return View("NonRemovableBook", id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Extensions;
using BookStore.Models;
using BookStore.Models.Books;
using BookStore.Models.Carts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartRepository _cartRepository;

        public CartController(ICartRepository cartRepository)
        {
            this._cartRepository = cartRepository;
        }

        public IActionResult Index() 
            => View(_cartRepository.GetAllCartItemsSortedAscBy(cartItem => cartItem.Book.Title));

        public IActionResult AddToCart(int id, bool? backToShopping)
        {
            _cartRepository.AddToCart(id);

            if (backToShopping != null && backToShopping == true)
            {
                return RedirectToAction(actionName: nameof(Index), controllerName: nameof(Book));
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromCart(int id)
        {
            _cartRepository.RemoveFromCart(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Views/Book/Create.cshtml
@model BookCreateViewModel

@{
  ViewBag.Title = "Book creation";
}

<h3 class="font-weight-normal mb-3 pt-2">Create a new book</h3>

<div class="row">
    <div class="col-lg-8">
        <form enctype="multipart/form-data" class="border rounded p-4 bg-light" asp-controller="Book" asp-action="Create" method="post">

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Title"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" asp-for="Title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Author"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" asp-for="Author" />
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Price"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" type="number" step="0.01" placeholder="0,0" asp-for="Price" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Description"></label>
                <div class="col-sm-9 col-md-10">
                    <textarea class="form-control" asp-for="Description">
                    </textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label asp-for="Photo" class="col-sm-3 col-md-2 col-form-label mb-sm-0"></label>
                <div class="custom-file col-sm-9 col-md-10">
                    <input asp-for="Photo" class="custom-file-input" />
                    <label class="custom-file-label">Select a file</label>
                </div>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="text-danger">Errors summary:</div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-row">
                <a asp-controller="Book" asp-action="Index" class="btn btn-secondary mr-1">Back to index</a>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>

</div>

@section Scripts {
    <script src="~/js/displayFormFileName.js"></script>
}

BookStore/Views/Book/Details.cshtml
@model Book

@{
  ViewBag.Title = "Book details";
  var PhotoPath = "~/images/" + (Model.PhotoUniqueName ?? SD.NoImage);
  var BookDescription = Model.Description ?? "Book description is not yet available";
}

<div class="row py-3 border-bottom border-dark">
    <div class="col-sm-8">
        <h1 class="font-weight-normal mb-3">Title: @Model.Title</h1>
        <h3 class="font-weight-normal mb-3">Author: @Model.Author</h3>
        <h3 class="mb-5">Price: @($"{Model.Price:C2}")</h3>
        <h5 class="font-weight-normal mb-0">Description: @BookDescription</h5>
    </div>

    <div class="col-sm-4">
        <img class="w-100" src="@PhotoPath" alt="Book cover" asp-append-version="true"/>
    </div>
</div>

<a asp-controller="Book" asp-action="Index" class="btn btn-secondary mt-3">Back to index</a>

BookStore/Views/Book/Edit.cshtml
@model BookEditViewModel

@{
    ViewBag.Title = "Book edition";
    var photoPath = "~/images/" + (Model.ExistingPhotoUniqueName ?? SD.NoImage);
}

<h3 class="font-weight-normal mb-3 pt-2">Edit the book</h3>

<div class="row">
    <div class="col-lg-8">
        <form enctype="multipart/form-data" class="border rounded p-4 bg-light" asp-controller="Book" asp-action="Edit" method="post">

            <input asp-for="Id" hidden/>
            <input asp-for="ExistingPhotoUniqueName" hidden/>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Title"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" asp-for="Title" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Author"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" asp-for="Author" />
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Price"></label>
                <div class="col-sm-9 col-md-10">
                    <input class="form-control" type="number" step="0.01" placeholder="0,0" asp-for="Price" asp-is-invariant="true"  />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label class="col-sm-3 col-md-2 col-form-label mb-sm-0" asp-for="Description"></label>
                <div class="col-sm-9 col-md-10">
                    <textarea class="form-control" asp-for="Description">
                    </textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-row">
                <label asp-for="Photo" class="col-sm-3 col-md-2 col-form-label mb-sm-0"></label>
                <div class="custom-file col-sm-9 col-md-10">
                    <input asp-for="Photo" class="custom-file-input" />
                    <label class="custom-file-label">Select a file</label>
                </div>
            </div>

            <div class="form-group form-row justify-content-center">
                <div class="col-sm-6 col-md-4">
                    <img class="w-100" src="@photoPath" alt="Book cover" asp-append-version="true" />
                </div>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="text-danger">Errors summary:</div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-row">
                <a asp-controller="Book" asp-action="Index" class="btn btn-secondary mr-1">Back to index</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>

</div>

@section Scripts {
    <script src="~/js/displayFormFileName.js"></script>
}

BookStore/Views/Book/Index.cshtml
@model IEnumerable<Book>

@{
    ViewBag.Title = "Bookshop - book index";
}

<div class="card-deck app-justify-content-evenly">
    @foreach (var book in Model)
    {
        var photoPath = "~/images/" + (book.PhotoUniqueName ?? SD.NoImage);

        <div class="card app-card--shadow app-card--width mt-3">
            <div class="card-body d-flex flex-column justify-content-end">
                <img class="card-img-top w-100" src="@photoPath" alt="Book cover" asp-append-version="true" />

                <h5 class="card-title font-weight-normal mt-2">@book.Title</h5>
                <p class="card-text mb-2">@book.Author</p>
                <h5 class="card-text">@($"{book.Price:C2}")</h5>
            </div>

            <div class="card-footer text-center">
                <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@book.Id" asp-route-backToShopping="true" class="btn btn-sm btn-success m-1">Add to cart</a>
                <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id" class="btn btn-sm btn-secondary">Details</a>
                <a asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id" class="btn btn-sm btn-secondary m-1">Edit</a>
                <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id" class="btn btn-sm btn-danger m-1">Delete</a>
            </div>
        </div>
    }
</div>

BookStore/Views/Book/NonRemovableBook.cshtml
@model int

@{
    ViewData["Title"] = "Non-removable book";
}

<div class="alert alert-danger mt-3">
    <h4>The Book with Id = @Model cannot be deleted.</h4>

    @if (ViewData["whyBookIsNonRemovable"] !=null 
        && ViewData["whyBookIsNonRemovable"].Equals("in-cart"))
    {
        <h5>It is in the shopping cart.</h5>
    }
    else
    {
        <h5>Most likely it does not exist or is a part of existing order.</h5>
    }
</div>

<a asp-controller="Book" asp-action="Index" class="btn btn-secondary">Go to book index</a>